### ISSUE TITLE
бро я либо тупой, либо у тебя баги

### ISSUE THREAD

**Issue by PUDGE133** [klybok-team/AudioInteract#1]
```csharp
Exiled.Events.Handlers.Server.RestartingRound += ServerRestartingRound;
Track.TrackFinished += OnTrackFinished;

private void ServerRestartingRound()
{
	RestartingRound();
}

private void OnTrackFinished(TrackFinishedEventArgs ev)
{
	FinishTrack();
}

public static void RestartingRound()
{
	//code
	FinishTrack();
}

public static void FinishTrack()
{
	//code
	Log.Debug(musicInstance == null);//console: true
	API.DestroyNPC(musicInstance);
	musicInstance = null;
}
```
в момент рестарта musicinstance может быть null. когда я в моменте рестарта передаю в метод API.DestroyNPC нулл, он ломается, потому что в самом начале в методе DestroyNPC идёт проверка if (musicInstance.Npc == null), однако прежде чем проверять нпс на нулл, ты должен проверить музикинстанц.

есть ещё одна проблема. нет pdb файла для того чтобы нормально дебажить это чудо програмистской мысли. сделай в настройках проекта следующее: свойства > сборка > дополнительно > сведения об отладке > ВСТРОЕННЫЙ. это сильно упростит жизнь людям.

и добавь пожалуйста меня в друзья в дискорде. ты зачем-то покинул сервер exiled и поменял свой никнейм и id. мой id scaletta2019

**Comment by adarkaz** [comment]
добавил, выпустил релиз

**Comment by PUDGE133** [comment]
не добавил в друзья. у меня есть какой-то супер баг который я вообще понять не могу как пофиксить.

**Comment by adarkaz** [comment]
такой же ник как тут в дс
